image: docker:stable

services:
- docker:dind

before_script:
- docker info

stages:
  - build
  - test

build:
  stage: build
  script:
    - if [ "$(docker container ls -aq -f name=api-concerns)" ]; then docker rm --force api-concerns; fi
    - docker build . -t api-concerns
    - docker network inspect api-concerns &>/dev/null || docker network create api-concerns
    - echo 'criou o network'

test:
  stage: test
  script:
    - echo "Stage testing"
