image: docker:stable

services:
  - docker:dind

before_script:
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD

stages:
  - build
  - test
  - deploy

build-image:
  stage: build
  script:
    - docker build --tag api-concerns .
    - docker tag api-concerns jesherpinkman/api-concerns:latest
    - docker push jesherpinkman/api-concerns:latest